### PR TITLE
OOPS! Studio! added undoing

### PR DESCRIPTION
**Pull request by OOPS-Studio**

### CODE REVIEW

**Comment by naclcaleb** [comment]
Like I said, it would be nice to have the key binding, but if you don't want to that's fine :P

**Comment by OOPS-Studio** [comment]
I just added it! :) Now I just have to figure out how to change this request to include it! ;3

**Comment by naclcaleb** [comment]
It does include it!
Thanks. I'll test it, and then see about merging.

**Comment by OOPS-Studio** [comment]
Wait! Nevermind! ;) It already did it for me! :) MERGE IT! XD (JK, you don't have to! ;))

**Comment by OOPS-Studio** [comment]
Okay! :) Sounds good! ;) (You can test it without merging!? 8O Kewlness! :))

**Comment by naclcaleb** [comment]
I'm testing it locally xD

It seems you have a spelling error on `Layer.js: 180`. `this.stroke` should be `this.strokes`

**Comment by OOPS-Studio** [comment]
1. Oh... XD
2. Oof. :P It's harder than it looks to add code into a huge project! >:( (Not really! ;3)

**Comment by naclcaleb** [comment]
Hmm...We have a problem.

It's still not working, but I have to go. I'll work on it when I can. 

Sorry, I didn't expect to have to leave so soon.

**Comment by OOPS-Studio** [comment]
1. *Facepalm* XD Of course there's a problem in the 5 lines of code I wrote! ;3
2. No probs! :) I'll try and figure it out while you're gone! ;)
3. No! It's all good, dude! :)

**Comment by naclcaleb** [comment]
Never mind, I figured it out.

It turns out that for whatever reason, you have to use `this.createRender()` instead of `this.updateRender()`. 

I also think it would be a good idea to combine the two `keydown` listeners with an `else if` and update the comments accordingly.

**Comment by OOPS-Studio** [comment]
1. I litirally just came here to let you know that it was a problem with using `updateRender()` instead of `createRender()` XD Great minds think alike! ;)
2. Yeah, you're right! :) I didn't think of that! ;)

**Comment by naclcaleb** [comment]
Ok, merging! Great job!

**Comment by OOPS-Studio** [comment]
Awww! ;3 Don't pretend that was an achievement! ;3 But, hey, I appreciate you taking the time to let me "help" you! ;) (You were very patient with me! :))

**Comment by naclcaleb** [comment]
Welcome :)

**Pull request merged**
