### PR TITLE
Fixed the over undoing/redoing issue.

### PR DESCRIPTION
**Pull request by OOPS-Studio**
Hopefully this fixes it! :) Let me know if it doesn't! ;3

### CODE REVIEW

**Comment by naclcaleb** [comment]
Ah yes, of course. Can't believe I missed that 🤔

**Comment by naclcaleb** [comment]
It mostly worked. The only thing I had to change was that line 178 said `this.undos.length` when it should have been `this.undone.length` :)

**Comment by OOPS-Studio** [comment]
Haha! XD My bad! ;3 Like I said, it's extremely hard for me to adapt to others' code for some reason! :)

**Comment by naclcaleb** [comment]
No problem!

**Comment by naclcaleb** [comment]
My latest update adds multiple layer support and also shows a snackbar notification when you undo/redo :)

**Comment by OOPS-Studio** [comment]
Oohhh! Nice! ;) I'll check it out! :)

**Comment by OOPS-Studio** [comment]
Hmm... So, the notifications are a nice touch, however, if I undo and redo a bunch of times, then they take a long time to catch up... Is there something you can do about that? :) (I sat and watched them for like 30+ sec! ;3)

**Comment by naclcaleb** [comment]
Yea, I saw the same problem and I'm working on it. I'm trying to see if there's a way of fixing that.

**Comment by naclcaleb** [comment]
Once I have the time I'll fix it. 

I think the trick will be creating a function `notify(message)` that will create its own `div` to notify with, and remove it when done. That way, they should all have their own timers for when they should come up and down.

**Comment by naclcaleb** [comment]
If you want to work on that, that would be great.

Here's the documentation on it: https://getmdl.io/components/#snackbar-section

If you don't understand what I mean, I'll just do it later.

**Comment by OOPS-Studio** [comment]
Hmmm... Do you have to use Snackbar? :) I think it'd be easier to just make it yourself! :) (Maybe that's just my trouble adapting to others' code talking! ;3) Also, it's been decided, I'm going to college to be a programmer. ;-;

**Comment by naclcaleb** [comment]
I don't,but unless this fix doesn't work, I don't want to get rid of it just yet. Google's code is probably going to be much cleaner and more efficient than mine would be...

**Comment by naclcaleb** [comment]
Oh, and as for college, does the college you're going to have many programming courses?

The one I go to only has C++ and Java, and not much for those.

**Comment by OOPS-Studio** [comment]
1. Yeah, okay, fine. XD
2. Well, it has one for database/infrastructure which is the one I'm going to do... (As far as I know) other than that, nope! :P
3. Why don't you use emojis? 😭

**Comment by OOPS-Studio** [comment]
3. HOW DARE YOU!? >:l

**Comment by naclcaleb** [comment]
3. I dare to do a lot of things...

**Comment by OOPS-Studio** [comment]
Fair enough.. o.O

**Comment by OOPS-Studio** [comment]
1. Okay! :) Good to hear! 👍 
2. Oh, sounds good! ;) What's the app? :P
3. Nice!! You got a Mac!? XD I just have a Dell running Windows! ;( (Actually, I really, really love it, so I don't know why I'm wining! XD)

**Comment by naclcaleb** [comment]
1. 👍 
2. It's called "The Meal Planner". My Mom wanted me to make it.
3. Yea, it's a 2007 iMac from my aunt, so I had to upgrade the CPU and Airport card to get it to run High Sierra so I could continue making my app with XCode. I'm doing a complete rewrite.
4. And nice about the Dell. I've never liked Windows, but especially not Windows 10. It's always going to be Mac or Linux for me! (probably mostly Linux, since Macs are so expensive...)

**Comment by OOPS-Studio** [comment]
2. Ah! Nice! ;)
3. Wow! Niiccce! ;) It's cool that your family requests things! :3 I can't get mine to! XD I'm kinda on my own as far as coding! :P
4. Hmm... Yeah, I could see that! :) Macs are more raw computers, you know? :P Windows are more polished! ;) (Not as good for developers! :P)

**Comment by naclcaleb** [comment]
3. Yea. 
4. Actually, I'd put it the other way around. Windows allows you much easier access to the "raw" part of your computer, while Macs have (or at least most people I've talked to agree) better and more polished graphics and UX. I particularly like that they don't obnoxiously update automatically at the least opportune times :P 

And then Linux is THE most raw computer. You have easy access to absolutely everything. You can make the graphics look like whatever you want, and it's generally very stable. (I like Linux :P)

**Comment by OOPS-Studio** [comment]
1. ;)
2. Hmm.... My experience is totally the opposite... XD I wonder why? :P Also, it's to my knowledge that you can turn off automatic updates! ;)
3. Yeah, I'd like that, too! :)

**Comment by OOPS-Studio** [comment]
1. Well, I see your point... But it wouldn't effect you! XD Just saying! ;3
2. Yeah, I could see that! ;) Apple does make it easy to have lots of devices linked together! :)
3. Yes! I totally agree! :P I think it's weird that they have a tablet mode for computers that don't even have a touchscreen! :P Plus, clicking tablet mode hardly changes anything, so it kinda makes me think that they could have done more for the PC! :P
4. Hmm... I haven't had Windows 10 on an old machine before... They've always been incompatible.. You're probably right, though! :)

**Comment by naclcaleb** [comment]
1. True :P 
2. Yea. So does Google, actually. They've been upping their game recently with the Pixelbook and Pixel phones.

3. Same. Although I think Google might be able to do better with ChromeOS. It's a great desktop OS (although very limited), but also is a great touch interface. Plus they've added support for running Android and Linux apps on it recently.

4. Yea. They're about to drop Windows 7 support...

**Comment by OOPS-Studio** [comment]
1. 👍 
2. Yeah! No kidding! :P I'm kinda scared of Google TBH.. XD
3. Oh! Wow! That's cool! ;) I haven't really looked into that at all, but it sounds interesting! :)
4. *Cries*

**Comment by naclcaleb** [comment]
1. ...
2. A lot of people seem to be. I honestly think they've been one of the better companies in terms of using their power and also user data and privacy. 
Facebook on the other hand...
3. Yea
4. Same.

**Comment by OOPS-Studio** [comment]
2. Yes. That's very true! ;) I gotta hand it to them on data leaks! XD But, still, if they turned on us, we couldn't stop 'em!
Facebook... Yikes... XD
3. :)

**Comment by naclcaleb** [comment]
2. Actually, we sort of could, considering the government keeps a close eye on big companies like them.
Yea...
3. :)

**Comment by OOPS-Studio** [comment]
Hehhe, or do they? >:)

**Comment by naclcaleb** [comment]
Google already had some trouble with the government this year when people found out that pictures of the president came up when you searched "idiot"...

**Comment by OOPS-Studio** [comment]
Wow. People really have no respect for their President. -_- Did republicans act like this when Obama was the president?

**Comment by naclcaleb** [comment]
Not that I was aware of.

I mean, of course there was a few, but not at this scale.

And of course it wasn't Google's fault. Google was just very good at finding what people were saying...

I find it very sad to be honest. People used to have more respect than they do now.

**Comment by naclcaleb** [comment]
Also, as to which OS is more "polished", take a look at these screenshots and tell me what you think:

Mac:
https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/highsierra/macbook-macos-high-sierra-launchpad-hero.jpg

Windows:
https://www.lifewire.com/thmb/P2E93fVLr4TNMBc-LHyn5d3-paQ=/768x0/filters:no_upscale():max_bytes(150000):strip_icc()/windows-10-14328-580797c43df78cbc285096a1.png

Mac:
https://cdn1.tekrevue.com/wp-content/uploads/2015/04/osx-finder-columns.jpg

Windows:
https://msegceporticoprodassets.blob.core.windows.net/asset-blobs/15414_en_1

Mac:
https://www.howtogeek.com/wp-content/uploads/2017/04/xspotlight-featured-search.png.pagespeed.gp+jp+jw+pj+ws+js+rj+rp+rw+ri+cp+md.ic.3gHUZtYQAz.jpg

Windows:
https://www.windowscentral.com/sites/wpcentral.com/files/styles/xlarge/public/field/image/2017/03/cu-cortanapickup.jpg?itok=aX90E5F7


Depending on your definition of "polished", I say macOS wins.

**Comment by OOPS-Studio** [comment]
Hmm.... I see what you mean... I think of "polished" to mean aesthetically pleasing, but I guess you could say higher-detail fits the word better! :) (Because, personally, I think the Windows looks better, but the Macs are more "polished") ;)
Also, Caleb, I was LITIRALLY just coming to check out your drawing program for the first time in like a month, and it just so happens to be the ONE time in the last month that you've commented here! ;3 What are the odds? :)

**Comment by naclcaleb** [comment]
1. Ok, I guess you could say that. Personally, I still like the macOS feel better, but I think that's just a different style. When I think "polished", I think elegant, smooth, and shiny, which is what I think about macOS. Windows is ok. The main thing I don't like is the way it names drives like "C:" and "D:" and all the other letters...

But I guess that's just because I'm used to Linux.

Anyhow, yes, I was wondering what happened  to you XD
I submitted a PR to one of your battleship game repos a while back and never got a response.

**Comment by OOPS-Studio** [comment]
1. Yeah, I agree, MacOS is more "polished" technically speaking! ;) I still like Windows better! :) It feels more clean and simple! :)

Probs! ;)
2. XD And me to you! :P
3. Really? ;-; I never got a notif! :( I'll go check it out! :)

**Comment by naclcaleb** [comment]
1. I think we're going to have to agree to disagree on that XD
It's not like I haven't used Windows though...I've only been using Linux for a couple of years or so. Before that I had to use Windows.

There's still one thing I always need to use Windows for: I often will put various Linux distros on a USB drive, but when I need to use it later, I need to clean it out first. So I go to Windows command prompt and type:
```
diskpart
list disk 
select disk <mydisk>
clean
create partition primary
format fs=fat32 quick
```

I'm sure there's an equivalent for macOS and Linux, I just haven't done the work of figuring it out yet.

2. XD I've actually been pretty active on GitHub lately...I've also been pushing my app code to a remote repo under "The Meal Planner" organization.

3. Interesting. Who knows what happened.

**Comment by OOPS-Studio** [comment]
1. Haha, I think so! ;)
Hehe, There **PROBABLY** is... XD Just too lazy? ;3 Me too! ;)
2. Haha, I've been checking my notifs on GitHub... But I haven't made any new repos for a while! :) Although, I'm working on an SVG making tool (Which is coming on superbly, BTW) and I plan to host that code on GitHub! ;) (Once I have a little more finished) So that'll be fun!! :D Why under Meal Planner? XD
3. Yeah... IDK! ;-; That's okay, though! :) As long as it doesn't happen again! 👍

**Comment by naclcaleb** [comment]
2. Because it's the "Meal Planner" app...

**Comment by OOPS-Studio** [comment]
Ohhhhhhh K... XD Makes sense! ;3

**Comment by naclcaleb** [comment]
XD

**Pull request merged**
